services:
  node1:
    image: mysql
    container_name: node1
    ports:
      - 3306:3306
    hostname: node1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - groupnet
    volumes:
      - d1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: >
      --server-id=1
      --log-bin=mysql-bin-1.log
      --enforce-gtid-consistency=ON
      --log-replica-updates=ON
      --gtid-mode=ON
      --transaction-write-set-extraction=XXHASH64
      --binlog-checksum=NONE
      --master-info-repository='TABLE'
      --relay-log-info-repository='TABLE'
      --plugin-load=group_replication.so
      --relay-log-recovery=ON
      --group-replication-start-on-boot=OFF
      --group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      --group-replication-local-address=node1:33061
      --group-replication-group-seeds='node1:33061,node2:33061,node3:33061'
      --loose-group-replication-single-primary-mode=ON
      --loose-group-replication-enforce-update-everywhere-checks=OFF

  node2:
    image: mysql
    container_name: node2
    ports:
      - 3307:3306
    hostname: node2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - groupnet
    volumes:
      - d2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: >
      --server-id=2
      --log-bin=mysql-bin-1.log
      --enforce-gtid-consistency=ON
      --log-replica-updates=ON
      --gtid-mode=ON
      --transaction-write-set-extraction=XXHASH64
      --binlog-checksum=NONE
      --master-info-repository='TABLE'
      --relay-log-info-repository='TABLE'
      --plugin-load=group_replication.so
      --relay-log-recovery=ON
      --group-replication-start-on-boot=OFF
      --group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      --group-replication-local-address=node2:33061
      --group-replication-group-seeds='node1:33061,node2:33061,node3:33061'
      --loose-group-replication-single-primary-mode=ON
      --loose-group-replication-enforce-update-everywhere-checks=OFF
  
  node3:
    image: mysql
    container_name: node3
    ports:
      - 3308:3306
    hostname: node3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - groupnet
    volumes:
      - d3:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: >
      --server-id=3
      --log-bin=mysql-bin-1.log
      --enforce-gtid-consistency=ON
      --log-replica-updates=ON
      --gtid-mode=ON
      --transaction-write-set-extraction=XXHASH64
      --binlog-checksum=NONE
      --master-info-repository='TABLE'
      --relay-log-info-repository='TABLE'
      --plugin-load=group_replication.so
      --relay-log-recovery=ON
      --group-replication-start-on-boot=OFF
      --group-replication-group-name=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      --group-replication-local-address=node3:33061
      --group-replication-group-seeds='node1:33061,node2:33061,node3:33061'
      --loose-group-replication-single-primary-mode=ON
      --loose-group-replication-enforce-update-everywhere-checks=OFF

  app:
    container_name: app
    image: hw2
    ports:
      - 8000:8000
    depends_on:
      node1:
        condition: service_healthy
    environment:
      MYSQL_HOST: node1
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    networks:
      - groupnet


networks:
  groupnet:
    driver: bridge
volumes:
  d1:
  d2:
  d3: