services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - 3306:3306
    hostname: mysqldb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - groupnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    networks:
      - groupnet

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - groupnet

  app:
    container_name: app
    image: jungche/yelp-like-app:v1
    ports:
      - 8000:8000
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MYSQL_PASSWORD: root
      REDIS_HOST: redis
      MYSQL_HOST: mysqldb
      RABBITMQ_HOST: rabbitmq

    networks:
      - groupnet

networks:
  groupnet:
    driver: bridge